### ISSUE TITLE
Klov app is not launching in the new docker build

### ISSUE THREAD

**Issue by ghost** [extent-framework/klov#60]
HI @anshooarora,
I am new to the klov server, I installed mongo DB in my local machine and start the docker compose.yml of klov but it gives a below error. 
![image](https://user-images.githubusercontent.com/45383305/88412361-0d2eab80-cdf7-11ea-97cf-137fa5f6160e.png)

docker compose.yml file 

version: '2'
services:
    klov:
        image: anshooarora/klov:1.0
        container_name: klov
        environment:
            - SPRING_DATA_MONGODB_URI=mongodb://localhost:27017
        ports:
            - 80:80

**Comment by ghost** [comment]
@anshooarora  can you please help me with this??

**Comment by anshooarora** [comment]
Can you try `127.0.0.1` instead of localhost?

**Comment by ghost** [comment]
@anshooarora 
I see no difference after changing from localhost to 127.0.0.1 
![image](https://user-images.githubusercontent.com/63581994/88452513-05b1e580-ce7d-11ea-9acf-ee01887363a1.png)

I need to show our klov reporter to one of our extreme clients. Do you have any other version of the docker image.?

**Comment by ghost** [comment]
@anshooarora  Dear any update on this?????

**Comment by anshooarora** [comment]
Ok, since you are on Windows and this being a linux container, there maybe an issue binding to "localhost". Try this as a workaround:

Do a `ipconfig` and use the ipv4 address:

```
Wireless LAN adapter Wi-Fi:

   Connection-specific DNS Suffix  . 
   IPv4 Address. . . . . . . . . . . : **10.0.0.2**
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 10.0.0.1
```

Use the IP address like:

```
version: '2'
services:
    klov:
        image: anshooarora/klov:1.0
        container_name: klov
        environment:
            - SPRING_DATA_MONGODB_HOST=10.0.0.2
        ports:
            - 80:80

```

If you get a connection refused, make sure mongod is accepting connections. You will have to set bind_ip under mongo.conf or start mongod with all incoming ips enabled:

```
mongod --bind_ip_all
```
